# -*- coding: utf-8 -*-
"""ESMFold2_Embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IuZeaW8-8F0mMpLPWhkvuAn6XOeupMQs
"""

!pip install git+https://github.com/facebookresearch/esm.git
!curl -O https://dl.fbaipublicfiles.com/fair-esm/examples/P62593_reprs.tar.gz
!tar -xzf P62593_reprs.tar.gz
!curl -O https://dl.fbaipublicfiles.com/fair-esm/examples/P62593.fasta
!pwd
#!ls

import random
from collections import Counter
from tqdm import tqdm

import torch
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

import esm

import scipy
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.svm import SVC, SVR
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression, SGDRegressor
from sklearn.pipeline import Pipeline
# "https://dl.fbaipublicfiles.com/fair-esm/models/esmfold_3B_v1.pt"
#esmfold_v1()

#OPTIONAL
#When there in no column name Affinity in the csv file
df = pd.read_csv('/data/amit/prot2fasta.csv')

#Add a new column 'Affinity' with random values between 1 and 10
df['Affinity'] = [random.randint(1, 10) for _ in range(len(df))]

updated_csv_file_path = '/data/amit/prot2fasta.csv'
df.to_csv(updated_csv_file_path, index=False)

#OPTIONAL
#Change the header name to 'ID', 'Target', 'Affinity'
df = pd.read_csv('/data/amit/prot2fasta.csv')
header = ['ID', 'Target', 'Affinity']
df.columns = header
df.to_csv('/data/amit/prot2fasta.csv', index=False)

dd = df.drop_duplicates(subset='ID')
dd.to_csv('/data/amit/prot2fasta.csv', index=False)

import csv
# Create a fasta file for protein sequence
with open('/data/amit/prot2fasta.csv', newline='') as csvfile:
    # Create a CSV reader object
    reader = csv.DictReader(csvfile, delimiter=',', quotechar='"')

    # Open the output fasta file
    with open('/data/amit/prot2fasta.fasta', 'w') as fastafile:
        # Loop through each row in the CSV file
        for row in reader:
            # Create the header line using the LigandID, PDB ID, and affinity fields
            #header = f">{row['Drug_ID']}|{row['Target_ID']}|{row['Affinity']}\n"
            header = f">{row['ID']}|{row['Affinity']}\n"
            # Write the header line to the output fasta file
            fastafile.write(header)

            # Write the sequence line to the output fasta file
            fastafile.write(row['Target'] + "\n")

!python extract.py esm2_t33_650M_UR50D /data/amit/prot2fasta.fasta /data/amit/prot2fasta/ --repr_layers 33 --include mean

FASTA_PATH = "/data/amit/prot2fasta.fasta" # Path to P62593.fasta
EMB_PATH = "/data/amit/prot2fasta/" # Path to directory of embeddings for P62593.fasta
EMB_LAYER = 33

ys = []
Xs = []
for header, _seq in esm.data.read_fasta(FASTA_PATH):
    scaled_effect = header.split('|')[-1]
    ys.append(float(scaled_effect))
    fn = f'{EMB_PATH}/{header}.pt'
    embs = torch.load(fn)
    Xs.append(embs['mean_representations'][EMB_LAYER])
Xs = torch.stack(Xs, dim=0).numpy()
print(len(ys))
print(Xs.shape)

Xs.shape, type(Xs[0])

np.save('/data/amit/results/unique_ESM_EMB_KIBA.npy', Xs)

emb = np.load('/data/amit/DAVIS/DAVIS_with_Emb/unique_target_ESM_EMB_DAVIS.npy')
emb.shape

np.save('/home/amit/BindingAffinity/EMBED/Davis/unique_ESM_EMB_DAVIS.npy', Xs)

dd['ESM_Embeddings'] = Xs.tolist()
dd

type(dd.iloc[1, 3])

dd = dd.drop(columns='Affinity')
dd

dd.to_csv('/data/amit/prot2fasta_ESM_Embeddings.csv', index=False)





